#!/bin/sh
#uname -snrvm
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;36m'
YELLOW='\033[0;33m'
WHITE='\033[0;37m'
NC='\033[0m'
echo "${YELLOW}-------------------------- 系统信息 --------------------------${NC}"
echo "${YELLOW}操作系统: ${WHITE}$(echo "$(sed 's/\\n//g;s/\\l//g' /etc/issue)")" || echo "操作系统: $(uname -o)${NC}"
echo "${YELLOW}主机名称: ${WHITE}$(hostname)${NC}"
echo "${YELLOW}内核版本: ${WHITE}$(uname -r)${NC}"
echo "${YELLOW}软件包数量: ${WHITE}$(dpkg --list | wc -l)${NC}"
echo "${YELLOW}CPU架构: ${WHITE}$(lscpu| awk '/Architecture:/ {print $NF}')${NC}"
echo "${YELLOW}CPU核心数: ${WHITE}$(lscpu| awk '/^CPU\(s\):/ {print $2}')${NC}"
echo "${YELLOW}核心线程数: ${WHITE}$(lscpu| awk '/Thread\(s\) per core:/ {print $NF}')${NC}"
echo "${YELLOW}CPU温度: ${WHITE}$(cat /sys/class/thermal/thermal_zone0/temp 2>/dev/null | awk '{print int($1/1000)}')°C${NC}"

ip_address=$(ip addr show | grep -w inet | grep -v 'lo$' | awk '{print $2}' | cut -d/ -f1 | awk '{ORS="\t";print}')
if [ -n "$ip_address" ]; then
echo "${YELLOW}-------------------------- 网络信息 --------------------------${NC}"
echo "${YELLOW}内网IP: ${GREEN}$ip_address${NC}"
curl_output=$(curl -s -m 6 ip.3322.net 2>&1 | sed '/^$/d') && [ -n "$curl_output" ] && {
echo "${YELLOW}公网IP: ${GREEN}$curl_output${NC}"; };
fi

echo "${YELLOW}-------------------------- EMCP信息 --------------------------${NC}"
mmc_info=$(cat /sys/class/mmc_host/mmc0/mmc0\:0001/life_time | awk '{printf "%.0f%%-%.0f%%",100-strtonum($1)*10,100-(strtonum($2)-1)*10};{if(strtonum($1)<8) {print " 正常";} else if(strtonum($1)<10) {print " 寿命即将耗尽"} else {print " 损坏"}}')
[ -n "$mmc_info" ] && echo "${YELLOW}EMCP寿命: ${BLUE}$mmc_info${NC}"
echo "${YELLOW}内存:  ${BLUE}$(free -m | awk 'NR==2{printf "%sMiB/%sMiB (%.2f%%)\n", $3,$2,$3*100/$2 }')${NC}"
echo "${YELLOW}Disk: ${BLUE}$(df -m | awk '/\/$/ {printf "%sMiB/%sMiB (%s)\n", $3,$2,$5 }')${NC}"

echo "${YELLOW}-------------------------- 运行信息 --------------------------${NC}"
uptime=$(uptime | sed 's/up/已运行:/g; s/mins/分钟/g; s/min/分钟/g; s/days/天/g; s/day/天/g; s/users/个登录用户/g; s/user/个登录用户/g; s/load average/平均负载/g')
echo "${RED}本地时间: $uptime${NC}"
echo ""
